/**
 * Pixel-art sprites, drawn facing right. One character = one pixel.
 * '.' is transparent; every other character maps to `palette`.
 * Eye pixels are 'e' (and 'i' for a highlight); when blinking they take the
 * colour of the `blink` palette key. Sprites are drawn 1:1 on the stages.
 * Edit the rows to redesign an animal; all rows must be the same width.
 */
export const SPRITES = {
  wolf: {
    id: 'wolf',
    blink: 'j',
    palette: { a: '#1a1c2c', b: '#687382', c: '#949fac', d: '#e8b8a0', f: '#4f5866', g: '#c3ccd6', h: '#454d5a', j: '#3a414d', e: '#ffcd75', l: '#8d98a6', m: '#efe6d2', o: '#0b0c14', p: '#d4c7ab', q: '#aa9c80', r: '#7f735d' },
    rows: [
      '.........................................a..aa.........',
      '........................................aa..aa.........',
      '........................................abaacda........',
      '........................................affbbda........',
      '.......................................afghhdhha.......',
      '.....................................aahggcccca........',
      '...................................aafhggcccjjja.......',
      '................................aaabffcccbgcbeega......',
      '.........aaaaaaaa.aaaaaaaaaaaaaafffffccccbccbccccaaa...',
      '........afbffbbbbabffblbbfbflblffffjbhhhmmmbbbccccccaoo',
      '.......ahccfffffffbffblbbffjfffbbbbbcbhppppmbbbbbccghoo',
      '......ahgcbbbjjjjfffffjjjfjjjjjbcccbbchqqpppppppppphha.',
      '.....aghccbhhbbbhhjjjjjjjjbhbbhhgccbbcbqrqqqqaqqhhha...',
      '....agbhchhgghhcccbbhbbbbbccccchcccccbmpprraa.aa.......',
      '...agghcchgggghcccccbccccccccccbhbbbbmggmqa............',
      '..aggcbhhgggggghbbbhhhbbbbbhhbbhhhbbbhggga.............',
      '.aggbcbhhggccgghbbbhhhbbbbbhhbbhhhbbhgggga.............',
      '.agbccbhhbcccbhhbbbppppppppqppmbhbbbhgggga.............',
      'accbccbahbcccbhbpppqqqqqqqqrqqpphhhhhcccga.............',
      'agcccba.acccccqqrqqaaaaaaaaaaaqqhhhhhccgca.............',
      'accbba..accccaqrrha...........aarrrrhcccca.............',
      'alllba..abcca.ahha..............arqrhhccca.............',
      'abfbba..abca..abha...............ahhbhccca.............',
      'affffa..abba..ahha...............ahcbhcbca.............',
      '.aaaa...abba..ahha...............ahbbhbhca.............',
      '.........abba..aha...............ahhhhbbha.............',
      '.........abba..aha...............ahhhhbbha.............',
      '.........abba..aha...............ahhhhbba..............',
      '..........aba..ahha..............ahhhabba..............',
      '..........ahha.ahha..............ahha.aha..............',
      '..........ahhhaahhha.............ahhhahhhaa............',
      '...........ahha.ahha..............ahhhaahha............',
      '............aa...aa................aaa..aa.............',
    ],
  },

  gorilla: {
    id: 'gorilla',
    blink: 'c',
    palette: { a: '#1a1c2c', b: '#5b6078', c: '#1d1f2c', d: '#3e4257', f: '#2b2e3f', g: '#c4c9d6', h: '#a08878', j: '#9ea4b8', l: '#7a8196', m: '#7e6858', e: '#120d0a', i: '#fbf6ee', o: '#5e4c40', p: '#403430' },
    rows: [
      '......................................aaa........',
      '....................................aabbbaa......',
      '..........................aaaaaaaa.abbbbbbba.....',
      '........................aabbbbbbbbacbbbbbbba.....',
      '......................aabbbbbbbbbbcbdfdddbbba....',
      '.....................abbbbbbbbbbbbdcdbfdddddba...',
      '....................agggggbbbbbbbbccccfdbdddbba..',
      '...................aggggggggbbbbccbbbbccbddhhha..',
      '...................ajlljjjgggddcbbbbbbbbchhhhhha.',
      '..............aaaaajjjjjjjjjgjdcbbbbbbbbbcccccca.',
      '............aajggggjggjjjjjjjlcdbbbbbbbbbbmmeimc.',
      '..........aaggjjljjgllbblblllbfddbbbbbbbbbmmmmma.',
      '.........aggjjljljjlllbblbllbfcdddfdbbbbbbmmoopap',
      '........aggjgjlblblllbbbbbbbfbcddddfdddbbboooopap',
      '.....aaajlgjllbblblbbbbbbbffddfcdbdfbdbbdbooooa..',
      '...aajlljgblllfbbbbbbffcffddddbcddfddddddbooppa..',
      '..aljgllllblbbdfffffcddfbbdbddfcfdfdddddddpppppp.',
      '.adllbllbbbbbcfddbddddddddfffffcffdddddffdaa.....',
      '.abdbbbbbbbbfffdddddddddfffffffcffddddbffa.......',
      'abddcbbcffdfddddbddddfffcfffcccccfddddddda.......',
      'adccbbbbccdddddddbdfffffcfffcccfcfbddddddda......',
      'adcbbbbbbcdddcffcfffffffffffffffcfcddddddda......',
      'acbbbbbbbbcffcffcfffffffffffffffcfcddddbdda......',
      'acfbfdfdbbcfffffffffcffffcfffffccfffddffdda......',
      'acfdfdfddfcfffffffffcffffcffffccccffffcfdda......',
      'acddbdddddcffcfcfffffcffffccccccccffffffcfa......',
      'acddddddddcffcfcfffffcffccccccccccffffffcfa......',
      '.acdddbdddcfccccccccccccccccccccccfffcfccfa......',
      '.acdddddddccccccccccccccccccccccccfffcfccfa......',
      '..affcffddccccccccccccccccaacccccccfffffcfa......',
      '..affcffffcccccaaaaaaaaaaa..accccccfffffcfa......',
      '..afffffcfcccca..............acccccfffffffa......',
      '...affffcfcccca..............accccccfffffffa.....',
      '...affffffccccca.............accccccccccfcca.....',
      '...affffffccccca.............accccccccccccca.....',
      '...accccfccccccfa.............accccccccccccca....',
      '....accccccfcccca.............accccccmcmcmcma....',
      '....aaaacaaaaaaaa.............aaaccaaaaccaaa.....',
      '........a........................aa....aa........',
    ],
  },

  grizzly: {
    id: 'grizzly',
    blink: 'd',
    palette: { a: '#1a1c2c', b: '#b0784a', c: '#8a5a36', d: '#442814', f: '#643e24', e: '#120d0a', i: '#fbf6ee', g: '#dcae7e', h: '#bb8858', j: '#0b0c14', l: '#8f6038', m: '#f4f4f4', o: '#ece0c4' },
    rows: [
      '................................aaaaaaaa......................',
      '..............................aabbbbbbbbaa....................',
      '............................aabbbbbbbbbbbbaa..................',
      '...........................abbbbbbbbbbbbbbbba.................',
      '..........................abbbbbbbbbbbccbbdbba................',
      '.........................abbbbbbcccccbccbcdddba...............',
      '.......aaaaaaaa..aaaaaaaabbbcfccccccccccccdbbddaa.aaa.........',
      '.....aabbbbbbbbaabbbbbbbbbbccfcfcfcccbffcbdcbdfccacfca........',
      '....abbbbbbbbbbbbbbbbbbbbbccbfcfcfccccffccfdbdfffdcdca........',
      '...abbbbbbbbbbbbbbbbbbbbbcccbbfccffccbffcfbdfdddddfddda.......',
      '..abbfccccffcccbbfcccccccbcbcbfccffcccffcfcdfcddbcdddcbaa.....',
      '..abcfccccffccbfcccccbccfccccccfcfccfcccbfbdffdbbbcfcbbba.....',
      '.abbcfdddcffbccfcccccbccfccccccfcfccfccccfcdfdccccccddccca....',
      '.abfddbbbddcffccfcccccfcbfccccccbccfdfffffddcdbcccccceicca....',
      '.acdbbbbbbbdffccfcccccfcbfbbcbffffffdfffffddfdddccccccfcca....',
      '.adbbbbbbbbbdbcffccbcccccccffffffdfffffffffdddbbddfccccgggaa..',
      'afdbbbbbbbbbdffffccccccccffffffffdfffffffffdbbbbbbdfffghhhhhjj',
      '.adbfbcccbbbdffffffdffffffddffdddfdfffffdfdbbbbbbbbdfhhhhhhhjj',
      '.adcfcccccccdffffffdffffffddffdddfdfffffdfdbbbffbbbdflhllllla.',
      '.adcccccccffdffdffdfffdfffffffffdfffdffffdcccfcccfbbdllllllla.',
      '.adcbcccccffdffdffdfffdfffffffffdfffdfffddcccfcccffbdaaddddd..',
      '..abfcfcfbcfdfffdfffffdffffdffffffffdfdddddcccccffcca....m.m..',
      '..acfcfbfccfdfffdfffffdffffdfffffffddddddddccccbffcca.........',
      '..acbccccfcfddddddfffffdffdddddddddddddddddfcbfffccca.........',
      '..acfccccfcfddddddddddddddddddddddddddddddddccfffccca.........',
      '...affdfdfdddddddddddddddddddddddddddddddddfffffcccca.........',
      '...affdfdfdddddddddddddddddddddddddaadddddddfffffffca.........',
      '...adffffdfdddddaaaaaaaaaaaaaaaaaaa..adddddddfffdffda.........',
      '...adffffdfdddda......................addddddfffdffda.........',
      '...adffffdfdddda......................adddddffdfdfffa.........',
      '...adffffdfdddda......................addddddfdfdfffa.........',
      '...addddddddddddaa....................adddddddddfffffaa.......',
      '...addddddddddddda.....................adddddddddddddffa......',
      '...aadddddddddddaa.....................aadddddaddddddoao......',
      '.....aaaaaaaoaoa.........................aaaaa.aaaaoao.o......',
    ],
  },

  eagle: {
    id: 'eagle',
    blink: 'd',
    palette: { a: '#1a1c2c', b: '#ffffff', c: '#e6e6ee', d: '#8e92a2', e: '#120d0a', f: '#ffd97a', i: '#ffcd75', g: '#f0b440', h: '#bcc0cc', j: '#c88a28', l: '#8f5e18', m: '#9a6a42', o: '#3a2214', p: '#52321e', q: '#74492c', r: '#7a5234', s: '#5a3a22', t: '#402818', u: '#2c1a0e' },
    rows: [
      '..........................aaaaaaaa........',
      '.........................abbbbbbbba.......',
      '........................abbbbbbbbbba......',
      '.......................abbbbbbcdddcba.....',
      '.......................abbcccccceecffaaa..',
      '.......................acccccccciccggggga.',
      '......................accccccccccccgggggga',
      '.......................acccccccchhhjjjjjga',
      '...................aaaacccccccchhhhjjlllja',
      '.................aammbccbcchcdhhhhhlaaaaaa',
      '...............aammmbbccchhdhdhhhhda.....a',
      '..............ammmmmccchhhhhhhhddda.......',
      '...........aaaommmmhbchhhhhhhhhdaa........',
      '...........ammmoooommmmhhhhhhhda..........',
      '..........ammmmmmmmmmmmmmmmhhdda..........',
      '..........appqqmmmmmmmmmmmmmddda..........',
      '..........appqqqpqmpqqqmpmpmddpma.........',
      '.........aqqqqqqpqqmppprrrpqooqqa.........',
      '.........arrrrrrrrrrrrrrrrpqopqqa.........',
      '.........arrrpppppoopppopqpqqoqqa.........',
      '.........appqqqqqqppqqqpqpoppoqqa.........',
      '........aqqqpooqqqqopoppppppppopa.........',
      '........aqqpoooppppopopsttspooopa.........',
      '........arssssssssssttttuutoooppa.........',
      '.......arsttoooooooooooooooooppa..........',
      '.......apooopoopppppppppooooppoa..........',
      '.......apooppooppppooooooooopoa...........',
      '.....aaqpoppoooouuuuuuuuooooooa...........',
      '....abmstuuuuuuuuuuuoooooooooa............',
      '...abcqtuooooooooooooooooooaa.............',
      '.aacccpooooooaooooooooooooa...............',
      'ahcccppooooaa.aaaaoooaaaoja...............',
      '.ahhhooodda.......ala...aja...............',
      '..adhdddaa.......ajja...ajja..............',
      '...addda.......aagjjjaaajjjga.............',
      '....aaa.......ajjjlllljlllljja............',
      '...............aaaaaaaaaaaaaa.............',
    ],
  },
};
