/**
 * Pixel-art sprites, drawn facing right. One character = one pixel.
 * '.' is transparent; every other character maps to `palette`.
 * Eye pixels are 'e' (and 'i' for a highlight); when blinking they take the
 * colour of the `blink` palette key. `hover` lifts a flier off the ground
 * (its shadow stays down). Sprites are drawn 1:1 on the stages.
 * Edit the rows to redesign an animal; all rows must be the same width.
 */
export const SPRITES = {
  wolf: {
    id: 'wolf',
    blink: 'q',
    palette: { a: '#1c1c26', b: '#181822', c: '#21212b', d: '#d1bfa2', e: '#efce7c', f: '#cab496', g: '#2a2830', h: '#64605e', j: '#37363b', l: '#434044', m: '#5e5b5a', o: '#4b494b', p: '#b49f86', q: '#6b6662', r: '#545150', s: '#786e64', t: '#86786a', v: '#bfaa8c', w: '#a28e79', x: '#91816f' },
    rows: [
      '..........................................aa..bb......',
      '....................................aacccadfaagha.....',
      '.................................bjljmmmoadpcqhga.....',
      '...............................gccjllhmmogdqghhlg.....',
      '...................aaaaaaaaaaaalmmmmmmmmljqhhhqhhb....',
      '................aacmmmmmmmllllllloommmmrhqqqqqqstqoa..',
      '..............aajloooommmmlolllllloormmhqqqqqrrctqlb..',
      '.............baalooooommmmlollllllommmrhqqqqqhmeahhc..',
      '...........bagogoooohmmhhhmlllllllmmmrvvvqqqqwwwwqqqb.',
      '........aacrooaoooohhhhhhmmmmmlrommmrqqffffqdddddddddg',
      '.......chmmrojchorqqqqfxsqmmmmmlhhmmrvvffdddpddddfdddc',
      '......oamhmoojghohqqqsvxxshmmmmoqqhmrpvwpffdwvffdtvdfa',
      '....bachmrrralhhhqqqqfsfffwmmmsmqqqqqrfvpwpxxcacjdddc.',
      '...bjmmmrrotboqqqhhtddgwpffvppswhqqqqqsvpwwgc....ccc..',
      '.ajqqroohxxmarqqqssffallgagpppptppqqsxpwxra...........',
      'amhqhhqxxqlagrqqxxfflrmhjc.cccxsvvqqqwxghjb...........',
      'chhhmqswxjjbgssqxvffghmhog..aacqvpqqswtcrjc...........',
      '.cjorxxoa..ctssfdfvcmmhmj......acgqwfcjhmga...........',
      '...aaca..actxvvvaabjmmrc........cgtwfaamhqqc..........',
      '........awwvvrcc.bbmmc..........ccwvfa.arqqta.........',
      '........appwab....bhha...........apffa..chqttc........',
      '........cppwa.....chha...........cvvfa...lrtxgb.......',
      '.......awppb.......ahhc..........apvfa....csthb.......',
      '.......cwssg.......aqqhac........bpppja....btxxac.....',
      '.......awwpb........amhqoa.......cswpvvc...cgxtwa.....',
      '.......cwsrb........accaaa........rswxpa....ccccc.....',
    ],
  },

  gorilla: {
    id: 'gorilla',
    blink: 's',
    palette: { a: '#20242e', b: '#31343b', c: '#2b2e36', d: '#5d5c5e', e: '#191a27', f: '#4b4b50', g: '#191a27', h: '#444449', j: '#1d1f2b', l: '#3e4046', m: '#73706f', o: '#131522', p: '#373940', q: '#3b3c42', r: '#242832', s: '#9e9892', t: '#8d8883', u: '#b3aca2', v: '#676465', w: '#565456', x: '#7b7774' },
    rows: [
      '..............................................ab..............',
      '............................................acddf.............',
      '...........................................gghhddd............',
      '..........................................jhhhclhdj...........',
      '.........................................ghhlllclhmg..........',
      '........................................ohllpppppblf..........',
      '......................................oclhlbbcqqpcqfg.........',
      '....................................oglllppcrsjbppbqhg........',
      '..................................golhqppbrrajtbbmsuuug.......',
      '................................gjrfffddvvjaahfcbvjoeeo.......',
      '..............................gacbffhffvmmmojobbpmhafg........',
      '.............................gacqffqffffwmmxoabcbftfusg.......',
      '............................gprrffppqhqpffxxxgbbbbcfwoo.......',
      '..........................gglqrrqpppqqqqplfdxmocbbrxsssg......',
      '.......................ggwdhlcarppcpbqqqlhlhxxorbblmtssg......',
      '...................oggoghwwflcaarbrprbqqqlqlhxoaarhmrsto......',
      '.................oohfdddddhllcrarrbbcrccqpqqqmojjrawwdo.......',
      '................gpdddddddhlllqragjrbppcarcqbpmooooogoo........',
      '...............ofdddddllllllqprjgojrbllqrrcqmogjjgj...........',
      '..............gfwdvmmmmpqppqppprajojblqlhdvvmxojjjcg..........',
      '.............olwwffvmmmbppppppppaagocqqqhflfvxxjjaqlg.........',
      '.............ohwwwfdmmmbbppppppprrjorpqplhhhdxxojrllr.........',
      '............gbwwqqqqlvvmgccrppppcraoocbpclqllvxoaabllg........',
      '............gbfqqllqqqmmoarccbrraaafoarbprppblxoaarphhg.......',
      '...........jobcppqqqllmmmorrraaarrddhorrrarcbpfcgaarbqbg......',
      '...........agcccpbqblllmxogaraaafvvddhoaraabbhdxfoaajlfl......',
      '...........agrccpcllhhlwmwgaaabvvvvvwfforrabhfwvxxojrplhl.....',
      '..........ojoacrbchlhllfmmgaarqvvvvdwffoaccqhhwdvxgacpqhhg....',
      '..........orgorcrbbllhllmmrgabdvvvddwgoorjpbhhqwwdxojrblhh....',
      '........ooaagogcaacbblldmmvojbbffwwqog..jarcclhcwfxcajcbhlg...',
      '.......gqprajgogcrrbpphmmmdogrppbaoo....grcraclhhqvxojrcqho...',
      '......oqlllrjjgojccrrpmmmmdooooog.......oaaccaqqphhxgaarbll...',
      '.....gpqllqcajjjojrllvvmvdro.............oaacarppllmvjaarpqg..',
      '....gapbqqbcajjjgjphvvvvhbjo..............oaracrpbqmmoajaclg..',
      '...ogrbcpbccajjjgghvvvvvbra...............ojaacrcrqvmojjjrlcg.',
      '..ggaracaccaajjooplffvvpbg.................ooaarrcplvogjjalqg.',
      '..ojaaaaraaajog.gpbqqqqpco...................ggrracpwg.ggbhlg.',
      '..aaagaaaaajo...jprrrppro.....................jgaarqcg.gcwaflg',
      '.gbfvhoaajgg...gjbaccccao......................orpaqxg.obdgffg',
      '.crfwdfjggg....oacarrragr.....................ojchvvmg.grwocdo',
      'ohjrlddjggg....oaraarjgjjo....................ogcfxmmj.oofgrdo',
      'ghqborwdrcao...oaargjxxwxvwj.................ohgoftmcaopgohfwg',
      '.gg..gjhlorcg..obbhwwmxxmjptg................ogqqphgjo.gjbggoo',
      '......ogoooo...goooggooggoooo.................ooooooga........',
    ],
  },

  grizzly: {
    id: 'grizzly',
    blink: 'r',
    palette: { a: '#36221f', b: '#30201f', c: '#a2653c', d: '#462a23', e: '#462a23', f: '#2d1d1b', g: '#261b1c', h: '#1d1a20', i: '#d6cfc7', j: '#975d37', l: '#7c4b2f', m: '#553325', o: '#4e2e23', p: '#71442d', q: '#8b5334', r: '#7e4d31', s: '#5c3726', t: '#653c28', u: '#262125', v: '#3d2621', x: '#b87b4a' },
    rows: [
      '.......................................ab...........................',
      '.......................................bcab.daa.....................',
      '......................fffffgh......gfbbccccjcccbgg..................',
      '...................abflcccccmofbbfflccccccclcccccmff................',
      '.................bfpjcccccccccccccccccqqrrrjllrccccjag..............',
      '................fstcccjjjjjjjcccccccjqqqrrrjrrrqjcccpa..............',
      '..............fbbcccccrrrllrqqccccccrrrrrrrrllrrljcccddg.baa........',
      '.............umqccjqrrrjqrrqjjrrcccrrlrrlllppttrrllasqjcbbspf.......',
      '............avccclrrrrrrrrrrrrrrrrrjrrrlllltlllrrtmfravjlcpvb.......',
      '............fcccrrrrrrrrrrlrrrrrrrrrrrlllltrlrllpsmbsaallccjm.......',
      '...........aaccqrrrrrrrrrrrrrrrrrrrrrllplptrrrrrtssatatrrcccmu......',
      '..........fbrclrrrrrllrrrllrrrrrrrrrrrllttrrllrrsvaotllrrrrrcsu.....',
      '.........gstrllllrrlltslrllrrrrrllrrrrlllptlplltdmmlrlrrrrrrrcvd....',
      '........udplllrlrrrrlllllllrrrrrlltlrrrllltsllpsbspplrrrrrrtqqjjh...',
      '........gdrlplrrrrrrllllllllllrrlpslrrrllltslllsbspplrrrrrtspqccu...',
      '.......gfmstlllrrrrrrllllltllllpstlrrrrlrrqssssooomtlrrrrrmeivrru...',
      '.......ggmlpsprrrrtllltlltllttlssssrrrlrrrrrsssofommtlrrltmoorxxx...',
      '.......abmstpprrlrlllqttpltspptsssmrrrrrrrljmmmmbdommsplsmssqxxxxx..',
      '......gbasssptrrllrllqtstltslttssmmllrrrrrljsmombvomomspssmmqxxxxduu',
      '......hadsssltlrrtllrqqmsssssssmddsllrrrrrrrptmdvffmmmmmmsplxxxxxhhh',
      '......hbvmmspllrllrptpqdossssssmaastllrrrrrlqtovvabfvooommruudxxxtu.',
      '......aaasssslpllrrttlqadmsssmsoavsspllrrrrljtvvddafbbavomrrd.......',
      '.....hvvassmmltpllrtsrqavmmsssmdbdsspllrrrrrjtbddvvfhh.fomrjxu......',
      '.....haaamssmprrlrlllrpavmmmmmovadssssllrrrrqofdbggh....hbddcx......',
      '......haommspspplrtprqfdommmodobmmosssslllrjfabhgbah.......ubf......',
      '.....uuaommmmssprltlrtfommmmmodboommsssltlltgggfbaabh...............',
      '.....hbmmommmssslltlqpfoommmmddfmmmmssslstrsgggbbaabh...............',
      '...hhgoooommmmmsttrptfvoommdgfgfdmmmssssstpgbbbbbaaoh...............',
      '...ffooooommmmmssslooffggggfu...gomssstttttfbbfbvvaohh..............',
      '.hgdoooooommmmmmssvfffffbbbgh...foomstltllahbbbbvvvoshh.............',
      '.hadooooommmmmmmmvbbfffbbbbg.....doossltrrf.gbaavvvdmhh.............',
      '.hddooodommmmmmmmgfffffbbbbg.....avossltrlf.hbvvvvvvmhh.............',
      'hbdddoooommmmmgfffffbbbbbbh......uooomtprlb.huavvvvvossh............',
      'bddddooooommfb..gfbbbbbbbh.......hoooospllb...hvvvvvossh............',
      'bddddddvahhh....gbbbfbghh.........hooommptb....hgvvvvvdshh..........',
      'bddddahhh.......gbbbbbbbba........haooommmmbu....ggvvvvdvvb.........',
      'bddddbhhh.......hbbbbbbabbh.......haooommssfgh....hvvvvvvdvuu.......',
      'bddddspa.h.......hbbbbbdagdh.......hdoomssptvsh....hvvvvtpolh.......',
      '.ggfffgffh.......hhhhhhhhhhh.......hfbbbaaagbuh.....guggugfbu.......',
    ],
  },

  eagle: {
    id: 'eagle',
    blink: 'r',
    hover: 8,
    palette: { a: '#221c24', b: '#171620', c: '#2f2122', d: '#452e28', e: '#221c24', f: '#53352b', g: '#3b2725', h: '#643e2d', i: '#ccaa85', j: '#754931', l: '#a87048', m: '#9b613b', o: '#885335', p: '#64544a', q: '#f1dbb6', r: '#faeacd', s: '#e0c29c', t: '#937967', u: '#ccaa85', v: '#b19275', w: '#d2812c', x: '#efac43' },
    rows: [
      '........aa.............................................',
      '...bc...bdc............................................',
      '...bdb...dfb...........................................',
      '...dgda..bggc..........................................',
      '....agfa..gfd..........................................',
      '.....bdhhbaddf.........................................',
      '.bb...bgfjdadhfb.......................................',
      '.agca..gdfjdcfjjb......................................',
      '.agddggagfhlmdhmma.....................................',
      '..bggfffccfjmlfhljg....................................',
      '...aggfffjgfjolholjfc..................................',
      'ba..gbdffhomjhllljlhha.................................',
      'cdaaabbffhhmllhllfmfjjba...............................',
      'bgdfffjjchhhjllhdhgddoogb..............................',
      '.bdgdfhjoomlllllhgddcfooha.............................',
      '..gaacdfffolllmhgfcddcdomob............................',
      'acgdffhhhoojjolooddgcdcdmmob...........................',
      '.adddhhjooollljmljddddgchjmb...........................',
      '..cdgdhhjjjjmmhhhhdddcdcgjocb................cc........',
      '..babaacdjhhommllmddddgddjjob...........aaadojja.......',
      '...bafhhhhommmohjmmccgccchhmd.........aghhohooc........',
      '..adddddddddddjjoljffggggcgjma....gcacjjjjojhc.........',
      '...agcccccjjjjjhlfoohggccggfmjb.aaadfjhojhjfa..........',
      '....abffffdffdddfmhhjccggcggjlabgdfffhhhhhda...........',
      '.....affdfddddhjhfoofcggggcgfmfaggdfffffhfg............',
      '......bccgcfffffcjhhgddcggcggolbgdfdghdghfb............',
      '........abddddcdfjjjgccgcggccdombgcdgdgffa.............',
      '........ddddccdddcdjhcgcgggcccfmmbcccgcfc..............',
      '........accadffgcdhhjgcgccgccaghmmbbaccgb..............',
      '.........bbdddccgdhhfccccccccccfhmmcacaaabfppff........',
      '..........gccccdddcfhjccccccccccgjmmmhhqrrrrrrrstd.....',
      '...........baddddcdddjgcaccccccccchoohfqqrrrrrrrrrp....',
      '...........bdddgcgdgcchdaccccccaacfhjhgsqrrrrrrqrrrsd..',
      '...........cgdacgddccahfccaccccbcgfhhhdpsqrrrrrrierrq..',
      '............aacddcccagahhccccaacffhhffgvqqrsrrrrrwatwa.',
      '.............bdgccgggadaagcccbcffhhfhhgtrssssussruuwxxg',
      '..............aaacgccgccaaabacffhfhhjfgassuuuvcaguoxxxc',
      '................baabggaaaabacffddhhhfhfcauvvbp....cwxxa',
      '.................aadgaaaaaacdfddfhhffhfcattap......b...',
      '....................baabbccdfgfhdfdhhdfgaaa............',
      '......................baccgfffgfdhhffdccgb.............',
      '...................aabacgdgddffffddddcdgc..............',
      '................dpsutccgfgdfdgfdfhohcggbaa.............',
      '...........cusqqrsttcgdgcgggdfgfhojoocbacga............',
      '........ddcvsrrrruttcdggcdggdccfjojoobbagdca...........',
      '........cqrrrruuuuutgaagfgddgcbffhooooaacdfab.....aa...',
      '........gccusqqsutttbvvgcccccabchhjoomacggffcb..axogfb.',
      '.........grqrruvutvttvaaabaaacbbdjdojohacggcmxxxxwmmcf.',
      '........gqqsuuquvvvtvpppppbbbb..bffjjhhbaccabjwwwob.b..',
      '........pqqusqsvsutvtttvtb......bgdddhhagsbaa.awa......',
      '.........avqqqsssvvttttvpp......bagggaoxxaxxxa.jj......',
      '.........aqrsuqqqvuvvtuvb........baccabwxxxgacbblg.....',
      '..........capqquvquutuvb...........bb..cwwoxb.b........',
      '...........cqquvqsutuub................bxf.ga..........',
      '............aadqvuasub.................bwp.............',
      '...............aabpab...................aa.............',
    ],
  },
};
